name: stock_all

on:
  schedule:
    - cron: "30 13 * * 1-5"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datetime
        pip install wheel
        pip install pandas
        pip install lxml
        pip install FinMind
        pip install requests
    - name: runpython
      run: python stock_Notify_price.py
